vcom Utils\Mux2.vhd -93
vcom Utils\Mux4.vhd -93
vcom Utils\Mux.vhd -93
vcom Utils\FullAdder.vhd -93
vcom Utils\NBitAdder.vhd -93
vcom Utils\Reg.vhd -93
vcom Utils\TwosComplement.vhd -93
vcom Utils\ShiftRegister.vhd -93
vcom Utils\BoothStep.vhd -93
vcom Utils\ModifiedBoothStep.vhd -93
vcom Utils\Types.vhd -93
vcom Utils/*.vhd -93
vcom CNN/RegFile.vhd -93
vcom CNN/CNNMuls.vhd -93
vcom CNN/*.vhd -93
vcom CNN/ControlUnit/NetworkController.vhd -93
vcom CNN/ControlUnit/LayerController.vhd -93
vcom CNN/ControlUnit/FilterController.vhd -93
vcom CNN/ControlUnit/SliceFilterController.vhd -93
vcom CNN/RegUnit.vhd -93
vcom CNN/TestBenches/*.vhd -93
vcom CNN/TestBenches/NetworkControllerTest.vhd -93