onerror {resume}
quietly virtual signal -install /accelerator/FCENT { (context /accelerator/FCENT )(labelReg_0_0 & labelReg_0_1 & labelReg_0_2 & labelReg_0_3 & labelReg_0_4 & labelReg_0_5 & labelReg_0_6 & labelReg_0_7 & labelReg_0_8 & labelReg_0_9 & labelReg_0_10 & labelReg_0_11 & labelReg_0_12 & labelReg_0_13 & labelReg_0_14 & labelReg_0_15 & labelReg_1_0 & labelReg_1_1 & labelReg_1_2 & labelReg_1_3 & labelReg_1_4 & labelReg_1_5 & labelReg_1_6 & labelReg_1_7 & labelReg_1_8 & labelReg_1_9 & labelReg_1_10 & labelReg_1_11 & labelReg_1_12 & labelReg_1_13 & labelReg_1_14 & labelReg_1_15 & labelReg_2_0 & labelReg_2_1 & labelReg_2_2 & labelReg_2_3 & labelReg_2_4 & labelReg_2_5 & labelReg_2_6 & labelReg_2_7 & labelReg_2_8 & labelReg_2_9 & labelReg_2_10 & labelReg_2_11 & labelReg_2_12 & labelReg_2_13 & labelReg_2_14 & labelReg_2_15 & labelReg_3_0 & labelReg_3_1 & labelReg_3_2 & labelReg_3_3 & labelReg_3_4 & labelReg_3_5 & labelReg_3_6 & labelReg_3_7 & labelReg_3_8 & labelReg_3_9 & labelReg_3_10 & labelReg_3_11 & labelReg_3_12 & labelReg_3_13 & labelReg_3_14 & labelReg_3_15 & labelReg_4_0 & labelReg_4_1 & labelReg_4_2 & labelReg_4_3 & labelReg_4_4 & labelReg_4_5 & labelReg_4_6 & labelReg_4_7 & labelReg_4_8 & labelReg_4_9 & labelReg_4_10 & labelReg_4_11 & labelReg_4_12 & labelReg_4_13 & labelReg_4_14 & labelReg_4_15 & labelReg_5_0 & labelReg_5_1 & labelReg_5_2 & labelReg_5_3 & labelReg_5_4 & labelReg_5_5 & labelReg_5_6 & labelReg_5_7 & labelReg_5_8 & labelReg_5_9 & labelReg_5_10 & labelReg_5_11 & labelReg_5_12 & labelReg_5_13 & labelReg_5_14 & labelReg_5_15 & labelReg_6_0 & labelReg_6_1 & labelReg_6_2 & labelReg_6_3 & labelReg_6_4 & labelReg_6_5 & labelReg_6_6 & labelReg_6_7 & labelReg_6_8 & labelReg_6_9 & labelReg_6_10 & labelReg_6_11 & labelReg_6_12 & labelReg_6_13 & labelReg_6_14 & labelReg_6_15 & labelReg_7_0 & labelReg_7_1 & labelReg_7_2 & labelReg_7_3 & labelReg_7_4 & labelReg_7_5 & labelReg_7_6 & labelReg_7_7 & labelReg_7_8 & labelReg_7_9 & labelReg_7_10 & labelReg_7_11 & labelReg_7_12 & labelReg_7_13 & labelReg_7_14 & labelReg_7_15 & labelReg_8_0 & labelReg_8_1 & labelReg_8_2 & labelReg_8_3 & labelReg_8_4 & labelReg_8_5 & labelReg_8_6 & labelReg_8_7 & labelReg_8_8 & labelReg_8_9 & labelReg_8_10 & labelReg_8_11 & labelReg_8_12 & labelReg_8_13 & labelReg_8_14 & labelReg_8_15 & labelReg_9_0 & labelReg_9_1 & labelReg_9_2 & labelReg_9_3 & labelReg_9_4 & labelReg_9_5 & labelReg_9_6 & labelReg_9_7 & labelReg_9_8 & labelReg_9_9 & labelReg_9_10 & labelReg_9_11 & labelReg_9_12 & labelReg_9_13 & labelReg_9_14 & labelReg_9_15 )} LabelReg
quietly virtual signal -install /accelerator/FCENT { (context /accelerator/FCENT )(labelReg_0_15 & labelReg_0_14 & labelReg_0_13 & labelReg_0_12 & labelReg_0_11 & labelReg_0_10 & labelReg_0_9 & labelReg_0_8 & labelReg_0_7 & labelReg_0_6 & labelReg_0_5 & labelReg_0_4 & labelReg_0_3 & labelReg_0_2 & labelReg_0_1 & labelReg_0_0 )} First15
quietly virtual signal -install /accelerator/FCENT { (context /accelerator/FCENT )(labelReg_1_15 & labelReg_1_14 & labelReg_1_13 & labelReg_1_12 & labelReg_1_11 & labelReg_1_10 & labelReg_1_9 & labelReg_1_8 & labelReg_1_7 & labelReg_1_6 & labelReg_1_5 & labelReg_1_4 & labelReg_1_3 & labelReg_1_2 & labelReg_1_1 & labelReg_1_0 )} Second15
quietly virtual signal -install /accelerator/FCENT { (context /accelerator/FCENT )(labelReg_2_15 & labelReg_2_14 & labelReg_2_13 & labelReg_2_12 & labelReg_2_11 & labelReg_2_10 & labelReg_2_9 & labelReg_2_8 & labelReg_2_7 & labelReg_2_6 & labelReg_2_5 & labelReg_2_4 & labelReg_2_3 & labelReg_2_2 & labelReg_2_1 & labelReg_2_0 )} Third15
quietly virtual signal -install /accelerator/FCENT { (context /accelerator/FCENT )(labelReg_3_15 & labelReg_3_14 & labelReg_3_13 & labelReg_3_12 & labelReg_3_11 & labelReg_3_10 & labelReg_3_9 & labelReg_3_8 & labelReg_3_7 & labelReg_3_6 & labelReg_3_5 & labelReg_3_4 & labelReg_3_3 & labelReg_3_2 & labelReg_3_1 & labelReg_3_0 )} Fourth15
quietly virtual signal -install /accelerator/FCENT { (context /accelerator/FCENT )(labelReg_4_15 & labelReg_4_14 & labelReg_4_13 & labelReg_4_12 & labelReg_4_11 & labelReg_4_10 & labelReg_4_9 & labelReg_4_8 & labelReg_4_7 & labelReg_4_6 & labelReg_4_5 & labelReg_4_4 & labelReg_4_3 & labelReg_4_2 & labelReg_4_1 & labelReg_4_0 )} Fifth15
quietly virtual signal -install /accelerator/FCENT { (context /accelerator/FCENT )(labelReg_5_15 & labelReg_5_14 & labelReg_5_13 & labelReg_5_12 & labelReg_5_11 & labelReg_5_10 & labelReg_5_9 & labelReg_5_8 & labelReg_5_7 & labelReg_5_6 & labelReg_5_5 & labelReg_5_4 & labelReg_5_3 & labelReg_5_2 & labelReg_5_1 & labelReg_5_0 )} Sixth15
quietly virtual signal -install /accelerator/FCENT { (context /accelerator/FCENT )(labelReg_6_15 & labelReg_6_14 & labelReg_6_13 & labelReg_6_12 & labelReg_6_11 & labelReg_6_10 & labelReg_6_9 & labelReg_6_8 & labelReg_6_7 & labelReg_6_6 & labelReg_6_5 & labelReg_6_4 & labelReg_6_3 & labelReg_6_2 & labelReg_6_1 & labelReg_6_0 )} Seventh15
quietly virtual signal -install /accelerator/FCENT { (context /accelerator/FCENT )(labelReg_7_15 & labelReg_7_14 & labelReg_7_13 & labelReg_7_12 & labelReg_7_11 & labelReg_7_10 & labelReg_7_9 & labelReg_7_8 & labelReg_7_7 & labelReg_7_6 & labelReg_7_5 & labelReg_7_4 & labelReg_7_3 & labelReg_7_2 & labelReg_7_1 & labelReg_7_0 )} Eighth15
quietly virtual signal -install /accelerator/FCENT { (context /accelerator/FCENT )(labelReg_8_15 & labelReg_8_14 & labelReg_8_13 & labelReg_8_12 & labelReg_8_11 & labelReg_8_10 & labelReg_8_9 & labelReg_8_8 & labelReg_8_7 & labelReg_8_6 & labelReg_8_5 & labelReg_8_4 & labelReg_8_3 & labelReg_8_2 & labelReg_8_1 & labelReg_8_0 )} Ninth15
quietly virtual signal -install /accelerator/FCENT { (context /accelerator/FCENT )(labelReg_9_15 & labelReg_9_14 & labelReg_9_13 & labelReg_9_12 & labelReg_9_11 & labelReg_9_10 & labelReg_9_9 & labelReg_9_8 & labelReg_9_7 & labelReg_9_6 & labelReg_9_5 & labelReg_9_4 & labelReg_9_3 & labelReg_9_2 & labelReg_9_1 & labelReg_9_0 )} Tenth15
quietly virtual signal -install /accelerator/FCENT { (concat_range (0 to 159) )( (context /accelerator/FCENT )(labelReg_0_15 & labelReg_0_14 & labelReg_0_13 & labelReg_0_12 & labelReg_0_11 & labelReg_0_10 & labelReg_0_9 & labelReg_0_8 & labelReg_0_7 & labelReg_0_6 & labelReg_0_5 & labelReg_0_4 & labelReg_0_3 & labelReg_0_2 & labelReg_0_1 & labelReg_0_0 & labelReg_1_15 & labelReg_1_14 & labelReg_1_13 & labelReg_1_12 & labelReg_1_11 & labelReg_1_10 & labelReg_1_9 & labelReg_1_8 & labelReg_1_7 & labelReg_1_6 & labelReg_1_5 & labelReg_1_4 & labelReg_1_3 & labelReg_1_2 & labelReg_1_1 & labelReg_1_0 & labelReg_2_15 & labelReg_2_14 & labelReg_2_13 & labelReg_2_12 & labelReg_2_11 & labelReg_2_10 & labelReg_2_9 & labelReg_2_8 & labelReg_2_7 & labelReg_2_6 & labelReg_2_5 & labelReg_2_4 & labelReg_2_3 & labelReg_2_2 & labelReg_2_1 & labelReg_2_0 & labelReg_3_15 & labelReg_3_14 & labelReg_3_13 & labelReg_3_12 & labelReg_3_11 & labelReg_3_10 & labelReg_3_9 & labelReg_3_8 & labelReg_3_7 & labelReg_3_6 & labelReg_3_5 & labelReg_3_4 & labelReg_3_3 & labelReg_3_2 & labelReg_3_1 & labelReg_3_0 & labelReg_4_15 & labelReg_4_14 & labelReg_4_13 & labelReg_4_12 & labelReg_4_11 & labelReg_4_10 & labelReg_4_9 & labelReg_4_8 & labelReg_4_7 & labelReg_4_6 & labelReg_4_5 & labelReg_4_4 & labelReg_4_3 & labelReg_4_2 & labelReg_4_1 & labelReg_4_0 & labelReg_5_15 & labelReg_5_14 & labelReg_5_13 & labelReg_5_12 & labelReg_5_11 & labelReg_5_10 & labelReg_5_9 & labelReg_5_8 & labelReg_5_7 & labelReg_5_6 & labelReg_5_5 & labelReg_5_4 & labelReg_5_3 & labelReg_5_2 & labelReg_5_1 & labelReg_5_0 & labelReg_6_15 & labelReg_6_14 & labelReg_6_13 & labelReg_6_12 & labelReg_6_11 & labelReg_6_10 & labelReg_6_9 & labelReg_6_8 & labelReg_6_7 & labelReg_6_6 & labelReg_6_5 & labelReg_6_4 & labelReg_6_3 & labelReg_6_2 & labelReg_6_1 & labelReg_6_0 & labelReg_7_15 & labelReg_7_14 & labelReg_7_13 & labelReg_7_12 & labelReg_7_11 & labelReg_7_10 & labelReg_7_9 & labelReg_7_8 & labelReg_7_7 & labelReg_7_6 & labelReg_7_5 & labelReg_7_4 & labelReg_7_3 & labelReg_7_2 & labelReg_7_1 & labelReg_7_0 & labelReg_8_15 & labelReg_8_14 & labelReg_8_13 & labelReg_8_12 & labelReg_8_11 & labelReg_8_10 & labelReg_8_9 & labelReg_8_8 & labelReg_8_7 & labelReg_8_6 & labelReg_8_5 & labelReg_8_4 & labelReg_8_3 & labelReg_8_2 & labelReg_8_1 & labelReg_8_0 & labelReg_9_15 & labelReg_9_14 & labelReg_9_13 & labelReg_9_12 & labelReg_9_11 & labelReg_9_10 & labelReg_9_9 & labelReg_9_8 & labelReg_9_7 & labelReg_9_6 & labelReg_9_5 & labelReg_9_4 & labelReg_9_3 & labelReg_9_2 & labelReg_9_1 & labelReg_9_0 ) )} Test001
quietly virtual signal -install /accelerator/IOChip/io/Interface/GlobalCounter { (context /accelerator/IOChip/io/Interface/GlobalCounter )(counterOutput_15_EXMPLR & counterOutput_14_EXMPLR & counterOutput_13_EXMPLR & counterOutput_12_EXMPLR & counterOutput_11_EXMPLR & counterOutput_10_EXMPLR & counterOutput_9_EXMPLR & counterOutput_8_EXMPLR & counterOutput_7_EXMPLR & counterOutput_6_EXMPLR & counterOutput_5_EXMPLR & counterOutput_4_EXMPLR & counterOutput_3_EXMPLR & counterOutput_2_EXMPLR & counterOutput_1_EXMPLR & counterOutput_0_EXMPLR )} CounerOutput
quietly WaveActivateNextPane {} 0
add wave -noupdate /accelerator/IOChip/io/Interface/GlobalCounter/loadData
add wave -noupdate /accelerator/IOChip/io/Interface/GlobalCounter/en
add wave -noupdate /accelerator/IOChip/io/Interface/GlobalCounter/load
add wave -noupdate /accelerator/IOChip/io/Interface/GlobalCounter/rst
add wave -noupdate /accelerator/IOChip/io/Interface/GlobalCounter/clk
add wave -noupdate /accelerator/IOChip/io/Interface/GlobalCounter/counterOutput
add wave -noupdate -radix hexadecimal -childformat {{/accelerator/IOChip/io/Interface/GlobalCounter/CounerOutput(15) -radix hexadecimal} {/accelerator/IOChip/io/Interface/GlobalCounter/CounerOutput(14) -radix hexadecimal} {/accelerator/IOChip/io/Interface/GlobalCounter/CounerOutput(13) -radix hexadecimal} {/accelerator/IOChip/io/Interface/GlobalCounter/CounerOutput(12) -radix hexadecimal} {/accelerator/IOChip/io/Interface/GlobalCounter/CounerOutput(11) -radix hexadecimal} {/accelerator/IOChip/io/Interface/GlobalCounter/CounerOutput(10) -radix hexadecimal} {/accelerator/IOChip/io/Interface/GlobalCounter/CounerOutput(9) -radix hexadecimal} {/accelerator/IOChip/io/Interface/GlobalCounter/CounerOutput(8) -radix hexadecimal} {/accelerator/IOChip/io/Interface/GlobalCounter/CounerOutput(7) -radix hexadecimal} {/accelerator/IOChip/io/Interface/GlobalCounter/CounerOutput(6) -radix hexadecimal} {/accelerator/IOChip/io/Interface/GlobalCounter/CounerOutput(5) -radix hexadecimal} {/accelerator/IOChip/io/Interface/GlobalCounter/CounerOutput(4) -radix hexadecimal} {/accelerator/IOChip/io/Interface/GlobalCounter/CounerOutput(3) -radix hexadecimal} {/accelerator/IOChip/io/Interface/GlobalCounter/CounerOutput(2) -radix hexadecimal} {/accelerator/IOChip/io/Interface/GlobalCounter/CounerOutput(1) -radix hexadecimal} {/accelerator/IOChip/io/Interface/GlobalCounter/CounerOutput(0) -radix hexadecimal}} -subitemconfig {/accelerator/IOChip/io/Interface/GlobalCounter/counterOutput_15_EXMPLR {-radix hexadecimal} /accelerator/IOChip/io/Interface/GlobalCounter/counterOutput_14_EXMPLR {-radix hexadecimal} /accelerator/IOChip/io/Interface/GlobalCounter/counterOutput_13_EXMPLR {-radix hexadecimal} /accelerator/IOChip/io/Interface/GlobalCounter/counterOutput_12_EXMPLR {-radix hexadecimal} /accelerator/IOChip/io/Interface/GlobalCounter/counterOutput_11_EXMPLR {-radix hexadecimal} /accelerator/IOChip/io/Interface/GlobalCounter/counterOutput_10_EXMPLR {-radix hexadecimal} /accelerator/IOChip/io/Interface/GlobalCounter/counterOutput_9_EXMPLR {-radix hexadecimal} /accelerator/IOChip/io/Interface/GlobalCounter/counterOutput_8_EXMPLR {-radix hexadecimal} /accelerator/IOChip/io/Interface/GlobalCounter/counterOutput_7_EXMPLR {-radix hexadecimal} /accelerator/IOChip/io/Interface/GlobalCounter/counterOutput_6_EXMPLR {-radix hexadecimal} /accelerator/IOChip/io/Interface/GlobalCounter/counterOutput_5_EXMPLR {-radix hexadecimal} /accelerator/IOChip/io/Interface/GlobalCounter/counterOutput_4_EXMPLR {-radix hexadecimal} /accelerator/IOChip/io/Interface/GlobalCounter/counterOutput_3_EXMPLR {-radix hexadecimal} /accelerator/IOChip/io/Interface/GlobalCounter/counterOutput_2_EXMPLR {-radix hexadecimal} /accelerator/IOChip/io/Interface/GlobalCounter/counterOutput_1_EXMPLR {-radix hexadecimal} /accelerator/IOChip/io/Interface/GlobalCounter/counterOutput_0_EXMPLR {-radix hexadecimal}} /accelerator/IOChip/io/Interface/GlobalCounter/CounerOutput
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {8824366 ps} 0}
quietly wave cursor active 1
configure wave -namecolwidth 271
configure wave -valuecolwidth 100
configure wave -justifyvalue left
configure wave -signalnamewidth 1
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ps
update
WaveRestoreZoom {8824050 ps} {8824937 ps}
