vsim -gui work.cnnwithram

add wave -position insertpoint sim:/cnnwithram/*
add wave -position insertpoint sim:/cnnwithram/CNNMap/coresMap/*
add wave -position insertpoint sim:/cnnwithram/CNNMap/controlUnitMap/*
add wave -position insertpoint sim:/cnnwithram/CNNMap/DMAControllerMap/*
add wave -position insertpoint sim:/cnnwithram/CNNMap/outbufferMap/*
add wave -position insertpoint sim:/cnnwithram/CNNMap/configMap/*

add wave -position insertpoint sim:/cnnwithram/CNNMap/coresMap/addersMap/*
add wave -position insertpoint sim:/cnnwithram/CNNMap/coresMap/mulsMap/*
add wave -position insertpoint  \
sim:/cnnwithram/CNNMap/coresMap/regFileMap/pagesOuts \
sim:/cnnwithram/CNNMap/coresMap/regFileMap/filtersOuts

add wave -position insertpoint  \
sim:/cnnwithram/CNNMap/DMAControllerMap/windowReadLogicEnt/aluNumberCounterClk

add wave -position insertpoint  \
sim:/cnnwithram/CNNMap/DMAControllerMap/windowReadLogicEnt/incUnitNumber

add wave -position insertpoint  \
sim:/cnnwithram/CNNMap/DMAControllerMap/windowReadLogicEnt/realIncUnitNumber

add wave -position insertpoint  \
sim:/cnnwithram/CNNMap/DMAControllerMap/windowReadLogicEnt/currentState

force -freeze sim:/cnnwithram/clk 0 0, 1 {50 ps} -r 100
force -freeze sim:/cnnwithram/rst 1 0
force -freeze sim:/cnnwithram/start 0 0

run


# weights ram
mem load -filltype value -filldata {00000000 } -fillradix binary /cnnwithram/weightsRam/ram(0)
mem load -filltype value -filldata {00000000 } -fillradix binary /cnnwithram/weightsRam/ram(1)
mem load -filltype value -filldata {10111000 } -fillradix binary /cnnwithram/weightsRam/ram(2)
mem load -filltype value -filldata {10110000 } -fillradix binary /cnnwithram/weightsRam/ram(3)
mem load -filltype value -filldata {01100000 } -fillradix binary /cnnwithram/weightsRam/ram(4)
mem load -filltype value -filldata {01100000 } -fillradix binary /cnnwithram/weightsRam/ram(5)
mem load -filltype value -filldata {01100000 } -fillradix binary /cnnwithram/weightsRam/ram(6)
mem load -filltype value -filldata {01100000 } -fillradix binary /cnnwithram/weightsRam/ram(7)
mem load -filltype value -filldata {01100000 } -fillradix binary /cnnwithram/weightsRam/ram(8)
mem load -filltype value -filldata {01100000 } -fillradix binary /cnnwithram/weightsRam/ram(9)
mem load -filltype value -filldata {01100000 } -fillradix binary /cnnwithram/weightsRam/ram(10)
mem load -filltype value -filldata {01100000 } -fillradix binary /cnnwithram/weightsRam/ram(11)
mem load -filltype value -filldata {01100000 } -fillradix binary /cnnwithram/weightsRam/ram(12)
mem load -filltype value -filldata {01100000 } -fillradix binary /cnnwithram/weightsRam/ram(13)


# image ram
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(0)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(1)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(2)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(3)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(4)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(5)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(6)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(7)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(8)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(9)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(10)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(11)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(12)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(13)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(14)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(15)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(16)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(17)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(18)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(19)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(20)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(21)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(22)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(23)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(24)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(25)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(26)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(27)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(28)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(29)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(30)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(31)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(32)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(33)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(34)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(35)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(36)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(37)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(38)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(39)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(40)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(41)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(42)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(43)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(44)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(45)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(46)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(47)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(48)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(49)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(50)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(51)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(52)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(53)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(54)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(55)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(56)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(57)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(58)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(59)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(60)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(61)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(62)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(63)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(64)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(65)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(66)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(67)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(68)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(69)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(70)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(71)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(72)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(73)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(74)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(75)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(76)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(77)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(78)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(79)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(80)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(81)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(82)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(83)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(84)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(85)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(86)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(87)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(88)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(89)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(90)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(91)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(92)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(93)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(94)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(95)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(96)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(97)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(98)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(99)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(100)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(101)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(102)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(103)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(104)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(105)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(106)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(107)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(108)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(109)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(110)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(111)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(112)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(113)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(114)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(115)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(116)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(117)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(118)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(119)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(120)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(121)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(122)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(123)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(124)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(125)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(126)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(127)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(128)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(129)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(130)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(131)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(132)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(133)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(134)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(135)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(136)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(137)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(138)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(139)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(140)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(141)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(142)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(143)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(144)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(145)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(146)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(147)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(148)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(149)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(150)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(151)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(152)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(153)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(154)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(155)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(156)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(157)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(158)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(159)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(160)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(161)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(162)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(163)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(164)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(165)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(166)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(167)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(168)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(169)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(170)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(171)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(172)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(173)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(174)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(175)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(176)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(177)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(178)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(179)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(180)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(181)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(182)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(183)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(184)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(185)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(186)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(187)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(188)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(189)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(190)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(191)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(192)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(193)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(194)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(195)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(196)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(197)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(198)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(199)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(200)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(201)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(202)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(203)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(204)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(205)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(206)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(207)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(208)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(209)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(210)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(211)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(212)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(213)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(214)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(215)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(216)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(217)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(218)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(219)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(220)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(221)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(222)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(223)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(224)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(225)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(226)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(227)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(228)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(229)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(230)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(231)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(232)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(233)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(234)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(235)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(236)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(237)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(238)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(239)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(240)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(241)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(242)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(243)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(244)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(245)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(246)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(247)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(248)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(249)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(250)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(251)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(252)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(253)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(254)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(255)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(256)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(257)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(258)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(259)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(260)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(261)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(262)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(263)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(264)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(265)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(266)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(267)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(268)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(269)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(270)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(271)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(272)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(273)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(274)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(275)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(276)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(277)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(278)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(279)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(280)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(281)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(282)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(283)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(284)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(285)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(286)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(287)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(288)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(289)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(290)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(291)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(292)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(293)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(294)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(295)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(296)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(297)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(298)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(299)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(300)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(301)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(302)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(303)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(304)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(305)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(306)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(307)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(308)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(309)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(310)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(311)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(312)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(313)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(314)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(315)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(316)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(317)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(318)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(319)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(320)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(321)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(322)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(323)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(324)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(325)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(326)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(327)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(328)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(329)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(330)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(331)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(332)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(333)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(334)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(335)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(336)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(337)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(338)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(339)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(340)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(341)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(342)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(343)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(344)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(345)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(346)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(347)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(348)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(349)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(350)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(351)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(352)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(353)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(354)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(355)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(356)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(357)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(358)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(359)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(360)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(361)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(362)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(363)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(364)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(365)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(366)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(367)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(368)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(369)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(370)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(371)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(372)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(373)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(374)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(375)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(376)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(377)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(378)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(379)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(380)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(381)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(382)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(383)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(384)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(385)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(386)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(387)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(388)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(389)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(390)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(391)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(392)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(393)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(394)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(395)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(396)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(397)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(398)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(399)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(400)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(401)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(402)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(403)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(404)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(405)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(406)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(407)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(408)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(409)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(410)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(411)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(412)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(413)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(414)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(415)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(416)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(417)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(418)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(419)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(420)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(421)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(422)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(423)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(424)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(425)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(426)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(427)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(428)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(429)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(430)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(431)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(432)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(433)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(434)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(435)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(436)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(437)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(438)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(439)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(440)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(441)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(442)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(443)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(444)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(445)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(446)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(447)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(448)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(449)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(450)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(451)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(452)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(453)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(454)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(455)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(456)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(457)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(458)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(459)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(460)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(461)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(462)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(463)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(464)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(465)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(466)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(467)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(468)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(469)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(470)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(471)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(472)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(473)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(474)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(475)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(476)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(477)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(478)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(479)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(480)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(481)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(482)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(483)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(484)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(485)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(486)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(487)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(488)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(489)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(490)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(491)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(492)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(493)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(494)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(495)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(496)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(497)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(498)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(499)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(500)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(501)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(502)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(503)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(504)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(505)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(506)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(507)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(508)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(509)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(510)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(511)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(512)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(513)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(514)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(515)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(516)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(517)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(518)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(519)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(520)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(521)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(522)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(523)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(524)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(525)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(526)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(527)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(528)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(529)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(530)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(531)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(532)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(533)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(534)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(535)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(536)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(537)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(538)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(539)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(540)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(541)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(542)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(543)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(544)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(545)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(546)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(547)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(548)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(549)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(550)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(551)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(552)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(553)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(554)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(555)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(556)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(557)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(558)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(559)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(560)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(561)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(562)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(563)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(564)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(565)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(566)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(567)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(568)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(569)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(570)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(571)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(572)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(573)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(574)
mem load -filltype value -filldata {0200} -fillradix hexadecimal /cnnwithram/windowRam/ram(575)




force -freeze sim:/cnnwithram/rst 0 0
force -freeze sim:/cnnwithram/start 1 0

run


run
run
run
run

run

run
run
run
run

run

#readBias